givery-bootcamp/dena-2024-team6

- backend/internal/entities/posts.go
- frontend/pnpm-lock.yaml
- frontend/src/pages/posts/detail/PostDetailRoute.tsx
投稿詳細ページのUIは完成していたが、APIとの繋ぎ込みが出来ていなかった
> 投稿詳細ページのロジック実装 

- frontend/src/pages/posts/PostsRoute.tsx
> fix: pages->posts ルーティング修正

- .github/workflows/backend.yml
- .github/workflows/backenddeploy.yml
- .github/workflows/frontend.yml
- docker/backend-ci.Dockerfile
バックエンドのアップデートがあればデプロイが動くようになる
バックエンドのアップデートがあればデプロイが動くようになる
> github actionの追加

- mysql/sql/insert.sql
> insertしたpasswordの可読性がなくなったのでコメントを追加

- backend/internal/controllers/post_controller.go
- backend/internal/controllers/update_post_controller.go
- backend/internal/interfaces/posts_repository.go
- backend/internal/middleware/router.go
- backend/internal/repositories/posts_repository.go
- backend/internal/usecases/post_usecase.go
- backend/internal/usecases/updete_post_usecase.go
> 投稿作成APIの実装

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/api/api.msw.ts
- frontend/src/api/api.ts
- frontend/src/api/model/index.ts
- frontend/src/api/model/loginRequest.ts
- frontend/src/api/model/post.ts
- frontend/src/api/model/user.ts
- frontend/src/app/AppRoute.tsx
- frontend/src/pages/posts/CreatePostRoute.tsx
- frontend/src/pages/posts/PostsRoute.tsx
- frontend/src/shared/libs/axios.ts
> 投稿作成画面の実装 

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/pages/posts/detail/PostDetailRoute.tsx
> 投稿をマークダウン対応する

- backend/internal/repositories/posts_repository.go
- frontend/src/api/api.ts
- frontend/src/api/model/post.ts
- frontend/src/api/model/user.ts
- frontend/src/app/AppRoute.tsx
- frontend/src/pages/posts/CreatePostRoute.tsx
- frontend/src/pages/posts/PostsRoute.tsx
- frontend/src/pages/posts/detail/PostDetailRoute.tsx
- frontend/src/pages/posts/update/UpdatePostRoute.tsx
Close #45
~~### このPRが対応してないタスク（issueを切った）~~
- #65 対応しました
- #66 対応しました
削除してから、一覧から消えるまでの時間が長いかも
> 投稿編集画面、削除の実装

- backend/internal/repositories/posts_repository.go
- frontend/src/api/api.ts
- frontend/src/api/model/post.ts
- frontend/src/api/model/user.ts
- frontend/src/app/AppRoute.tsx
- frontend/src/pages/posts/CreatePostRoute.tsx
- frontend/src/pages/posts/PostsRoute.tsx
- frontend/src/pages/posts/detail/PostDetailRoute.tsx
- frontend/src/pages/posts/update/UpdatePostRoute.tsx
> 投稿詳細画面へのコメント機能追加

- backend/api/controller/post_controller.go
- backend/api/router/router.go
- backend/api/schema/auth_schema.go
- backend/api/schema/post_schema.go
- backend/application/delete_post_usecase.go
- backend/domain/repository/post_repository.go
- backend/infrastructure/store/post_repository_impl.go
- backend/main.go
リアーキ後のPost削除実装ができていなかった
Post削除実装
deleted atを参照するようにした（論路削除）
> Feature/backend refactor/delete post

- backend/api/controller/auth_controller.go
- backend/config/config.go
- backend/main.go
- docker-compose.yml
> 本番環境クッキー周りのエラー解消

- backend/infrastructure/store/store.go
> SQL周りの設定修正

- backend/infrastructure/store/store.go
> Allow Native Trueにした

- frontend/src/api/hooks.msw.ts
- frontend/src/api/hooks.ts
- frontend/src/api/model/index.ts
- frontend/src/api/model/schemaCommentResponse.ts
- frontend/src/api/model/schemaCreateCommentRequest.ts
- frontend/src/api/model/schemaCreatePostRequest.ts
- frontend/src/api/model/schemaErrorResponse.ts
- frontend/src/api/model/schemaLoginRequest.ts
- frontend/src/api/model/schemaMutationSchema.ts
- frontend/src/api/model/schemaPostResponse.ts
- frontend/src/api/model/schemaUpdateCommentRequest.ts
- frontend/src/api/model/schemaUpdatePostRequest.ts
- frontend/src/api/model/schemaUserResponse.ts
- frontend/src/app/App.scss
- frontend/src/pages/signin/SigninRoute.tsx
> ログイン画面のUI刷新

- backend/config/config.go
> cookie domainハードコーディング

- backend/domain/model/user.go
> `User`のドメイン修正

- backend/application/signup_usecase.go
> ユーザ名の文字種制限を撤廃する

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/pages/posts/PostsRoute.tsx
[#91](https://github.com/givery-bootcamp/dena-2024-team6/issues/91)
> 投稿作成画面のUI刷新

- backend/api/router/router.go
> fix comments

- frontend/pnpm-lock.yaml
- frontend/src/app/AppRoute.tsx
- frontend/src/pages/posts/CreatePostRoute.tsx
- frontend/src/pages/posts/PostsRoute.tsx
> 新規投稿作成画面のUI刷新

- backend/infrastructure/store/user_repository_impl_test.go
> Userリポジトリの単体テストを書く

- backend/infrastructure/store/comment_repository_impl_test.go
- backend/infrastructure/store/init_test.go
> Commentリポジトリの単体テストを追加

- frontend/src/api/hooks.msw.ts
- frontend/src/pages/posts/detail/PostDetailRoute.tsx
> コメント周りの挙動変更

- frontend/src/pages/posts/PostsRoute.tsx
> 盛り上がり度の0.5秒更新
